version: "3.8"

services:
  mongodb:
    container_name: mongodb
    image: mongo:5.0.2
    restart: unless-stopped
    env_file: ./.env
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
    #   - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
    ports:
      - 7017:27017
    volumes:
      - db:/data/db
  app:
    depends_on:
      - mongodb
    container_name: parking-lot-api
    build: .
    restart: unless-stopped
    env_file: ./.env
    ports:
      - 9000:9000
    environment:
      - DB_HOST=mongodb
    #   - DB_USER=$MONGODB_USER
    #   - DB_PASSWORD=$MONGODB_PASSWORD
    #   - DB_NAME=$MONGODB_DATABASE
    #   - DB_PORT=$MONGODB_DOCKER_PORT
    stdin_open: true
    tty: true

volumes:
  db:
